language: node_js
node_js:
  - "7"

install:
  - npm install -g gulp
  - npm install -g firebase-tools

after_success:
  - firebase deploy --project friendgen --token 1/tdk_B7R3nIJTxfyEXIvkerwrQawA4-9wlZjDqqUKtfU