;let matchingUsers = [
    {
        "id":'faceBook_id',
        "name":"matt",
        "score":92,
        "matchingCategories":[
            "category1",
            "category2",
            "category3"
        ],
        "matchingLikes":[
            "like1",
            "like2",
            "like3"
        ]
    },
    {
        "id":'faceBook_id',
        "name":"jon",
        "score":93,
        "matchingCategories":[
            "category1",
            "category2",
            "category3"
        ],
        "matchingLikes":[
            "like1",
            "like2",
            "like3"
        ]
    },
    {
        "id":'faceBook_id',
        "name":"james",
        "score":98,
        "matchingCategories":[
            "category1",
            "category2",
            "category3"
        ],
        "matchingLikes":[
            "like1",
            "like2",
            "like3"
        ]
    }
]

;let dbUserStructure = {
    "id":'faceBook_id',
    "name":'John Doe',
    "likes":[
        "Fishing",
        "Hiking",
        "Swimming",
        "BascketBall",
        "Dodgeball"
    ],
    "categories":[
        "category1",
        "cagetory2",
        "category3"
    ],
    "location":{
        "lat":12.3456,
        "lon":65.4321
    },
    "lastFix":20000,
    "dataURL":'randomHexStuffWeCantUnderstand'
}